# Generated by Django 4.2.3 on 2023-08-07 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_postblog_delete_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postblog',
            options={'ordering': ('-published',)},
        ),
        migrations.AlterField(
            model_name='postblog',
            name='status',
            field=models.CharField(choices=[('publish', 'Publish'), ('draft', 'Draft')], max_length=10),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Blog.postblog')),
            ],
            options={
                'ordering': ('create_at',),
            },
        ),
    ]
